"""upgrade

Revision ID: 3038ab266c76
Revises: 8ff3437545ff
Create Date: 2025-07-10 12:21:34.369055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3038ab266c76'
down_revision: Union[str, Sequence[str], None] = '8ff3437545ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_model_user_id_key'), 'task_model', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('task_model_user_id_key'), 'task_model', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
