"""update

Revision ID: a8f7d055d535
Revises: 59a830daf7bb
Create Date: 2025-07-10 13:05:37.000396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f7d055d535'
down_revision: Union[str, Sequence[str], None] = '59a830daf7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_model', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task_model', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_model', type_='foreignkey')
    op.drop_column('task_model', 'user_id')
    # ### end Alembic commands ###
