"""update

Revision ID: dee152f9de41
Revises: 6c09b80e5108
Create Date: 2025-07-10 14:02:23.855812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee152f9de41'
down_revision: Union[str, Sequence[str], None] = '6c09b80e5108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_table_full_name_key'), 'user_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_table_full_name_key'), 'user_table', ['full_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
