"""update

Revision ID: e5284c1ac643
Revises: c4303809a1a0
Create Date: 2025-07-10 11:59:45.724082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5284c1ac643'
down_revision: Union[str, Sequence[str], None] = 'c4303809a1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user_table', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user_table', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user_table', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.alter_column('user_table', 'password',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user_table', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user_table', 'full_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
